In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [4]:
df=pd.read_csv("/Churn_Modelling T3.csv")

In [5]:
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [7]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [9]:
df.describe()

         RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [10]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [16]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(8000, 13)
(2000, 13)
(8000,)
(2000,)

In [14]:
xtrain,xtest,ytrain,ytest=train_test_split(df.drop('Exited',axis=1),df['Exited'],test_size=0.2,random_state=42)

In [17]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

# One-hot encode 'Geography' and 'Gender'
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)

# Define features (X) and target (y)
X = df.drop('Exited', axis=1)
y = df['Exited']

# Split the data into training and testing sets
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale numerical features
numerical_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'EstimatedSalary']

scaler = StandardScaler()
xtrain[numerical_cols] = scaler.fit_transform(xtrain[numerical_cols])
xtest[numerical_cols] = scaler.transform(xtest[numerical_cols])

# Train a Logistic Regression model
model = LogisticRegression(random_state=42)
model.fit(xtrain, ytrain)

# Make predictions
ypred = model.predict(xtest)

# Evaluate the model
accuracy = accuracy_score(ytest, ypred)
classification_rep = classification_report(ytest, ypred)
conf_matrix = confusion_matrix(ytest, ypred)

print(f"Model: Logistic Regression")
print(f"Accuracy: {accuracy:.4f}")
print(f"Classification Report:\n{classification_rep}")
print(f"Confusion Matrix:\n{conf_matrix}")

Model: Logistic Regression
Accuracy: 0.8115
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.56      0.20      0.30       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000

Confusion Matrix:
[[1544   63]
 [ 314   79]]

### Random Forest Classifier

In [18]:
from sklearn.ensemble import RandomForestClassifier

# Train a Random Forest model
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(xtrain, ytrain)

# Make predictions
rf_ypred = rf_model.predict(xtest)

# Evaluate the model
rf_accuracy = accuracy_score(ytest, rf_ypred)
rf_classification_rep = classification_report(ytest, rf_ypred)
rf_conf_matrix = confusion_matrix(ytest, rf_ypred)

print(f"Model: Random Forest Classifier")
print(f"Accuracy: {rf_accuracy:.4f}")
print(f"Classification Report:\n{rf_classification_rep}")
print(f"Confusion Matrix:\n{rf_conf_matrix}")

Model: Random Forest Classifier
Accuracy: 0.8665
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.76      0.47      0.58       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.86      0.87      0.85      2000

Confusion Matrix:
[[1550   57]
 [ 210  183]]

### Gradient Boosting Classifier

In [19]:
from sklearn.ensemble import GradientBoostingClassifier

# Train a Gradient Boosting model
gb_model = GradientBoostingClassifier(random_state=42)
gb_model.fit(xtrain, ytrain)

# Make predictions
gb_ypred = gb_model.predict(xtest)

# Evaluate the model
gb_accuracy = accuracy_score(ytest, gb_ypred)
gb_classification_rep = classification_report(ytest, gb_ypred)
gb_conf_matrix = confusion_matrix(ytest, gb_ypred)

print(f"Model: Gradient Boosting Classifier")
print(f"Accuracy: {gb_accuracy:.4f}")
print(f"Classification Report:\n{gb_classification_rep}")
print(f"Confusion Matrix:\n{gb_conf_matrix}")

Model: Gradient Boosting Classifier
Accuracy: 0.8675
Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.75      0.49      0.59       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.76      2000
weighted avg       0.86      0.87      0.86      2000

Confusion Matrix:
[[1543   64]
 [ 201  192]]

### Comparison of Models

Here's a summary of the performance metrics for each model:

In [20]:
print("\n--- Model Comparison ---")
print(f"Logistic Regression Accuracy: {accuracy:.4f}")
print(f"Random Forest Accuracy: {rf_accuracy:.4f}")
print(f"Gradient Boosting Accuracy: {gb_accuracy:.4f}")

print("\nLogistic Regression Classification Report:\n", classification_rep)
print("\nRandom Forest Classification Report:\n", rf_classification_rep)
print("\nGradient Boosting Classification Report:\n", gb_classification_rep)

--- Model Comparison ---
Logistic Regression Accuracy: 0.8115
Random Forest Accuracy: 0.8665
Gradient Boosting Accuracy: 0.8675

Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.96      0.89      1607
           1       0.56      0.20      0.30       393

    accuracy                           0.81      2000
   macro avg       0.69      0.58      0.59      2000
weighted avg       0.78      0.81      0.77      2000


Random Forest Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.76      0.47      0.58       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.86      0.87      0.85      2000


Gradient Boosting Classification Report:
               precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.75      0.49      0.59       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.76      2000
weighted avg       0.86      0.87      0.86      2000